@startuml Diagrama Secuencia

 Aplicacion -> Creador: creadorT()
activate Creador

 Creador -> Tarea: crearNuevaTarea()
activate Tarea

 Creador <-- Tarea: crearNuevaTarea() OK
deactivate Creador


 Aplicacion -> Tarea: agregarNuevaTarea(tarea)
 Tarea -> Lista: agregarNuevaTarea(tarea)
activate Lista
 Tarea <-- Lista: agregarNuevaTarea(tarea) OK
 Aplicacion <-- Tarea: agregarNuevaTarea(tarea) OK
deactivate Tarea










@enduml