@startuml Diagrama Secuencia


Aplicacion -> Creador: 1: creadorT(titulo, desc, fecha, prio, cat, et)
activate Creador

create Tarea
Creador -> Tarea: 2: crearNuevaTarea(titulo, desc, fecha, prio, cat, et)

deactivate Creador

activate Tarea
Aplicacion -> Tarea: 3: agregarNuevaTarea(tarea)
Tarea -> Lista: 4: agregarNuevaTarea(tarea)

activate Lista
Tarea <-- Lista: 5: agregarNuevaTarea(tarea)
Aplicacion <-- Tarea: 6: agregarNuevaTarea(tarea)

Lista -> Tarea: 7: delete(tarea)
destroy Tarea

@enduml