@startuml Diagrama Secuencia

/' Opción 1: '/

Aplicacion -> Creador: creadorT(titulo, desc, fecha, prio, cat, et)
activate Creador

create Tarea
Creador -> Tarea: crearNuevaTarea(titulo, desc, fecha, prio, cat, et)

deactivate Creador

activate Tarea
Aplicacion -> Tarea: agregarNuevaTarea(tarea)
Tarea -> Lista: agregarNuevaTarea(tarea)
activate Lista
Tarea <-- Lista: agregarNuevaTarea(tarea) OK
Aplicacion <-- Tarea: agregarNuevaTarea(tarea) OK

Lista -> Tarea: delete(tarea)
destroy Tarea


/' Opción 2: 

Aplicacion -> Creador: creadorT()
activate Creador

create Tarea
Creador -> Tarea: crearNuevaTarea()
deactivate Creador

Aplicacion -> Lista: agregarNuevaTarea(tarea)
activate Tarea

activate Lista

Lista -> Tarea: delete(tarea)

deactivate Lista
destroy Tarea

'/


@enduml